-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: autopep8-wrapper
        args:
        - -i
    -   id: end-of-file-fixer
    -   id: flake8
        language_version: python3.6
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/Magicjarvis/pre-commit-python-sorter
    rev: v1.0.5
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
